name: AWS Practical

on:
  push:
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region eu-west-1
          
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 884257732597.dkr.ecr.eu-west-1.amazonaws.com

      - name: Push Docker Image to ECR
        run: |
          docker tag my-image-name:${{ github.sha }} 884257732597.dkr.ecr.eu-west-1.amazonaws.com/my-image-name:${{ github.sha }}
          docker push 884257732597.dkr.ecr.eu-west-1.amazonaws.com/my-image-name:${{ github.sha }}

      - name: Deploy App to ECS
        run: |
          aws ecs update-service --cluster mygitcluster --service mygitservice --task-definition ecs-task-definition.json
